// P-9 and P-10 page checks: each carries its doc copy verbatim (headline, sub, body, the
// five pillars, the home card's tagline and small line), a breadcrumb through Our
// Technology, series cards that open their range in the catalogue and show a real image
// (no photo slot), sibling links, the labelled placeholder for technical data (the line-up
// itself now lives in the catalogue), no console errors, nothing hidden without JS.
async (page) => {
  const BASE = 'http://127.0.0.1:8765';
  const norm = (s) => s.replace(/[’‘]/g, "'").replace(/\s+/g, ' ').trim();
  const PAGES = {
    'p-9-ester': {
      h1: 'P-9 ESTER BASED TECHNOLOGY', crumb: 'P-9 ESTER',
      must: ['PROPRIETARY ESTER TECHNOLOGY FOR ENGINE OILS & RACING LUBRICANTS.', 'Modern Automotive & Racing Performance', 'Engineered for advanced automotive and extreme motorsport applications.',
        'P-9 ESTER Based Technology is the core formulation architecture behind PRINCE LUBRICANTS flagship FS1 Series, FS1 EUROGEN Series and FSR Racing Series. It integrates high-polar ester chemistry with high-performance Group V synthetic base stocks and state-of-the-art additive systems to enhance surface affinity, lubricant film retention, thermal-oxidative stability and volatility control. This synergistic formulation architecture is developed to maintain film integrity and improve engine shield under increased temperatures, heavy loads and sustained mechanical load stress.',
        'SUPERIOR FILM STRENGTH', 'Resilient lubricant film supports surface separation and protection under extreme loads and mechanical stress.',
        'POLAR MOLECULAR PROTECTION', 'Strong surface affinity supports persistent lubricant coverage on critical components.',
        'BROAD-TEMPERATURE PERFORMANCE', 'Stable lubrication across cold ambient, extreme heat and sustained operating conditions.',
        'RAPID COLD-START PROTECTION', 'Immediate circulation and surface retention support protection during critical start-up conditions.',
        'ENHANCED ENGINE CLEANLINESS', 'Natural ester solvency supports deposit and sludge control and cleaner internal engine surfaces.',
        'FS1 SERIES', 'FS1 EUROGEN SERIES', 'FSR SERIES'],
      series: ['../../products/passenger-car/#fs1', '../../products/passenger-car/#fs1-eurogen', '../../products/motorsport/#racing-motor-oils'],
      siblings: ['../p-10-ester/', '../#p-plus-synthese', '../'],
    },
    'p-10-ester': {
      h1: 'P-10 ESTER BASED TECHNOLOGY', crumb: 'P-10 ESTER',
      must: ['DEDICATED ESTER TECHNOLOGY FOR POWERFUL 4T ENGINES.', 'High-Performance Motorcycle Engineering', 'Dedicated technology engineered for powerful 4T applications.',
        'Motorcycle engines operate within an exceptionally demanding lubrication environment. High specific power output, sustained high RPM and compact engine construction generate intense thermal loading, while many motorcycles rely on the same oil to lubricate the engine, gearbox and wet clutch. P-10 ESTER Based Technology is developed specifically for these conditions. Polar ester chemistry supports oil-film retention at elevated temperatures, while strong resistance to volatility and thermal degradation helps preserve lubricant integrity. Carefully controlled frictional and rheological properties provide the shear resistance, clutch compatibility and protection demanded by high-performance motorcycle powertrains.',
        'HIGH-LOAD FILM PROTECTION', 'Ester polarity supports persistent lubricant films across heavily loaded engine and transmission contact surfaces.',
        'HIGH-TEMPERATURE VISCOSITY SUPPORT', 'Thermally stable ester chemistry helps preserve oil film performance as operating temperatures increase.',
        'SUSTAINED THERMAL ENDURANCE', 'Supports prolonged lubricant performance under the continuous heat generated by high-output engines.',
        'THERMAL DEGRADATION RESISTANCE', 'Heat resistance properties help resist lubricant breakdown during severe and sustained operating conditions.',
        'LOW-DEPOSIT PERFORMANCE', 'Natural ester solvency supports deposit control and cleaner lubrication under demanding operations.',
        'MAXX GOLD SERIES'],
      series: ['../../products/motorcycle/#maxx-gold-4t'],
      siblings: ['../p-9-ester/', '../#p-plus-synthese', '../'],
    },
  };
  const out = { pass: true };
  const errors = [];
  page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
  page.on('pageerror', (e) => errors.push(String(e)));
  await page.setViewportSize({ width: 1440, height: 900 });
  for (const [slug, spec] of Object.entries(PAGES)) {
    errors.length = 0;
    await page.goto(`${BASE}/technology/${slug}/`, { waitUntil: 'networkidle' });
    await page.waitForTimeout(1200);
    const src = await page.evaluate(async () => {
      const doc = new DOMParser().parseFromString(await (await fetch(location.href, { cache: 'no-store' })).text(), 'text/html');
      return { main: doc.querySelector('main')?.textContent ?? '', h1: [...doc.querySelectorAll('h1')].map((h) => h.textContent) };
    });
    const text = norm(src.main);
    const r = {};
    r.missing = spec.must.map(norm).filter((s) => !text.includes(s));
    r.h1 = src.h1.map(norm);
    r.crumb = await page.evaluate((c) => {
      const b = document.querySelector('.breadcrumb');
      return !!b && !!b.querySelector('a[href="../"]') && b.querySelector('[aria-current="page"]')?.textContent.trim() === c;
    }, spec.crumb);
    r.series = await page.evaluate((hrefs) => hrefs.filter((h) => !document.querySelector(`main a[href="${h}"]`)), spec.series);
    r.siblings = await page.evaluate((hrefs) => hrefs.filter((h) => !document.querySelector(`main a[href="${h}"]`)), spec.siblings);
    r.placeholder = await page.evaluate(() => !!document.querySelector('main .ph .ph-tag'));
    r.lineupPending = text.includes('product line-up');
    await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
    await page.waitForTimeout(800);
    await page.evaluate(() => document.querySelector('#series .p-card')?.scrollIntoView());
    await page.waitForTimeout(800);
    r.seriesImages = await page.evaluate(() => {
      const grid = document.querySelector('#series');
      const imgs = grid ? [...grid.querySelectorAll('img')] : [];
      return { slots: grid ? grid.querySelectorAll('.photo-slot').length : -1, loaded: imgs.filter((i) => i.complete && i.naturalWidth > 0).length, cards: grid ? grid.querySelectorAll('.p-card').length : 0 };
    });
    r.consoleErrors = [...errors];
    const ctx = await page.context().browser().newContext({ javaScriptEnabled: false, viewport: { width: 1440, height: 900 } });
    const nojs = await ctx.newPage();
    await nojs.goto(`${BASE}/technology/${slug}/`, { waitUntil: 'load' });
    r.noJsHidden = await nojs.evaluate(() => [...document.querySelectorAll('main h1, main h2, main h3, main p, main li, main a')]
      .filter((e) => !e.closest('[aria-hidden="true"]'))
      .filter((e) => { const s = getComputedStyle(e); return parseFloat(s.opacity) < 1 || s.visibility === 'hidden'; })
      .map((e) => e.tagName + ':' + e.textContent.trim().slice(0, 40)));
    await ctx.close();
    r.pass = r.missing.length === 0 && r.h1.length === 1 && r.h1[0] === spec.h1 && r.crumb &&
      r.series.length === 0 && r.siblings.length === 0 && r.placeholder && !r.lineupPending &&
      r.seriesImages.slots === 0 && r.seriesImages.loaded === r.seriesImages.cards && r.consoleErrors.length === 0 && r.noJsHidden.length === 0;
    out[slug] = r;
    out.pass = out.pass && r.pass;
  }
  return out;
}
